sudo: required
language: node_js
node_js:
- '4'
services:
- docker
script:
- bash build_npm.sh
deploy:
  provider: npm
  email: ellery-newcomer@utulsa.edu
  on: 
    tags: true
  api_key:
    secure: LEO5i2Hkj22HP5/D0ym3JWqpXSZ3R635/LsSRSsbIb+La4GI/1JDcmZdVdqfeenK89Jz26PEVuoQv7+CJ97ht9/0F7EXekmvsEO9e2xB0KJd+FCS6ajhAgEV7bsIKQpshGUtevm/pYNMar+N63DMvnkNMO+vfJMYqorMxlTsuDcLPbeyLItDgN3lw7JRONzxvq86HUIU/WRwfwt2xlaAw8iMLY6IcBGHns+hcamBEjLCsTAkBf69w2R4gsFrQarxPSs2PlYOKwFJHxbQI1fnGlO+ixKJXs5CEs4+J81L3cjnC6FaNo/0A42zuD1eLgMlIrVP1X0HSYSuQeCbccnic4eXw9FOPLoX6BrLQVk8gh9jDLjHxDgb6HRMa3TL6mJco6K/Nw2CMc5Mpwo5j6VdYL9KLBYXh+8YuoaOWOFZz+OyTi/xAuTRnDXwwPfZT2BHMGFTNwL6PC9leNnAta+zkoZaae+nWkAA+t9BRIiNHS3zm0j6JQbCx/5unfMBsSVdf/83tSvYcez2F5XY8axaWc2Aqu2ebCQZl4fJ+uanyzXrIAGoDdL/dEhv9DO1442ryYSFbGFck/MBgrf0TTkNuX/zpakIZtaqHfL6iAQjLEm8DF8PbrH5IyimmraH1aREP+NUQpD4BRQrlJaXDm5RqOX8v3EwdErWIfaDjGgv9G8=
#addons:
    #    sauce_connect:
    #    username: "aurelia-mask"
    #    access_key:
    #        secure: "daF/wUbscwgMdGpD8Qih/cJtt3Fqau5/kFdpXBI0LUlL9cXAjgaVl2lsJe7bNa67lgRglSJ5yRlkG/Inx/ck6JC6kzMLrO1iijb24x3cP9s1kMxPiia9PyNXcG9BijayF0PGydkJPi2HvTkoBJh4hWTfOmIKo7/X+dgeNDxM1EYd2NnNX6cX29ylJhykj5IM3COVCMH7HJGEC3dQEAbsU5VAzkK07ya709vS0u3rW7KakzE77ROI7qOUZPTVHWnfxPU3gBEAix95jKvNu99us3osawl+vA/d191z/VDnaFVdzy0izNsOW2eOs0luH0ow2HmKAU1OE48H/Ll6nHPBo8HO/q2Yf9evDn8HsehxdEoDm+3SPaTx+twTaLOS7rSSFBOZzQCF0KlBgrrdtxeS0UoRjUdKx5mcZysNj/BcPgjDPvGylvXrBG4eVWDRpLnWl1I9Svib0vwT4QXFrvq3CQSAMaRVf+4tv3dIfBkAM/q0A7nRIXmeczJXgK5RyJGY6j3UxAXxQxKC6T0hT3wvYc4ET8DmadEtNOpTTATe9uneWd2ExcE1rpKXh6L7JgAYmEDKldLuEsxUVpQM766sz2edDp3e1JlT8JyAk6SwUr+Ys9YVzCxfl0be5LCmJ7z0u8cPxOIMgwFM/tGNgog/PUTFKklWPNHZTogn8P1bPqk="
