sudo: required
language: node_js
node_js:
- '4'
services:
- docker
script:
- bash build_npm.sh
deploy:
  skip_cleanup: true
  provider: npm
  email: ellery-newcomer@utulsa.edu
  on: 
    tags: true
  api_key:
    secure: "dHKbMjWaIFBwkdxZ+8F+zyqKA9Y0MzXMXzIaIovc3FHQoKiRiPIqCshBkJ3OWO1JOHK35PpXCcc6DONm3l3nOjtF+DCjtiP/Yeek6yGziKJR0cS70dpngJAzj6V7fVuWfC6fG/jjLDc0r3VGporDsxoRlK9dEaN+ze2T1oJghZ58iFrhE0MhUdxSx4N+ybvrmn2vMMVAM30yY2lNlLtsprkyA7/9U/xmaBDSX7Nk9cRIrcVOdl8mXT/ALhRTO2y6jNMixEy4Z4hrKpzpBOpB4WrheKkJM18BCLTFBnrrlstdMiBB4CzYCggHFdgNq7LFVAaqk/AdasSTO3FwgZx+pgAWJg49jwWJ7DojW/K9cFV43S0JZrCWfQ4+joJ9enFkjjaNEV3clIqc9AV2aA5c7quDu8oN4KWTkR6C4wn1v0nX+qcPXCLuJrWeWA8y5LQeodUyuutojg18kpRdwD7vChJ3ykU0PJ0KQXJd0doAHWJCxSqg1jK5KEtdWEPr2DNqTgjrMeTLuCi05ZiCQ1qHpfgvp0hIZ97KYJGgmt7if/StMBzAJp0cZDh0ktzZHtTnkyw9oNtUm/390806bNFrIwqft3H430h+WZpAzy1CpP11j7n1YChfvuPgAagH6jtRcLSra2EPzXa7NkzKPwlPp+x8aJcFExxRewjnJOH63zI="
